-- phpMyAdmin SQL Dump
-- version 3.4.11.1deb1
-- http://www.phpmyadmin.net
--
-- Värd: 10.0.227.78
-- Skapad: 13 jan 2016 kl 16:56
-- Serverversion: 5.5.34
-- PHP-version: 5.4.6-1ubuntu1.8

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Databas: `133425-admin`
--

-- --------------------------------------------------------

--
-- Tabellstruktur `animal`
--

CREATE TABLE IF NOT EXISTS `animal` (
  `id` varchar(20) COLLATE utf32_swedish_ci NOT NULL,
  `info` text COLLATE utf32_swedish_ci NOT NULL,
  `image` varchar(20) COLLATE utf32_swedish_ci NOT NULL,
  `eats` text COLLATE utf32_swedish_ci NOT NULL,
  `extra` text COLLATE utf32_swedish_ci NOT NULL,
  `name` varchar(20) COLLATE utf32_swedish_ci NOT NULL,
  `bor` text COLLATE utf32_swedish_ci NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf32 COLLATE=utf32_swedish_ci;

--
-- Dumpning av Data i tabell `animal`
--

INSERT INTO `animal` (`id`, `info`, `image`, `eats`, `extra`, `name`, `bor`) VALUES
('cat', 'Katter är kända för att göra lite som de själva vill. Men de kan också vara väldigt gosiga. De pratar genom att jama, fräsa och spinna. Katter är smarta och har lätt för att lära sig nya saker.\r\nKatter pratar också med kroppen. Om katten burrar upp svansen och har öronen bakåt är den arg eller rädd. En katt som piskar med svansen är irriterad. Om svansen står rakt upp är katten glad. Svansen hjälper också till att hålla balansen. En katt spinner för att visa att den mår bra. En rädd katt kan också spinna. Då gör den det för att bli lugnare. Det finns många olika sorters katter i många olika färger. En katt kan ha kort päls, lång päls eller vara helt naken!', 'cat', 'Ute i naturen äter katter gärna möss, sorkar och småfåglar. De är väldigt duktiga jägare som smyger på sitt byte. Även om de får god mat hemma vill de gärna jaga om de får möjlighet till det.\r\nHemma ska katten få torrfoder och rent vatten. Den kan också få burkmat. Katter är väldigt känsliga för nya saker. Därför vill de flesta katter helst ha samma mat varje dag.\r\nKatter är duktiga jägare. De ser bra i mörkret och kan höra en liten mus på långt håll. På nosen och benen har de morrhår. Med dem kan de känna rörelser i luften. Katter är också väldigt snabba och viga. Från att ha suttit stilla kan de hoppa jättehögt, nästan ända upp till taket i ett vanligt rum.', 'Den äldsta katt man vet om blev 38 år gammal!\r\nEn katt landar nästan alltid på tassarna.\r\nKatter som är vita och har blå ögon är ofta döva. Det betyder att de inte hör någonting.', 'Katt', 'Katten är det vanligaste husdjuret i Sverige. Det finns både utekatter och innekatter. Helst vill katter vara ute och jaga när det är mörkt, så på dagarna sover de mest. En katt kan bli 20 år!\r\nDet finns många hemlösa katter som far illa. En del föds i det vilda och är skygga för människor. Andra slängs ut då ägaren har tröttnat på dem. Men som tur är finns det människor som hjälper katter också. '),
('chicken', 'Hönan är den vanligaste fågeln i världen. Det finns många olika sorters höns i många olika storlekar och färger. Av hönan får vi ägg och kött.\r\nHönans ungar kallas kycklingar. Hanen kallas tupp. Tupparna är större och mer färgglada än hönorna. De har också större kam och längre stjärtfjädrar. Det har de för att imponera på hönorna.\r\nEn höna lägger 150-200 ägg per år. Om man plockar bort äggen lägger hon nya. Annars blir de kycklingar. När honan ruvar vill hon vara i fred och värma äggen. Kycklingarna tar sig ur äggen själva med näbben. Sen får de stanna i boet två dagar innan de får komma ut till de andra.', 'chicken', 'Hönor äter det mesta. Till exempel småkryp, säd, matrester, frukt och grönsaker. De behöver också vatten att dricka. Hönan letar mat genom att sprätta med fötterna bland löven på marken.\r\nÄggen vi får av hönsen smakar olika beroende på vad de äter. Gulan kan också få olika färg.', 'Hönor sover på en pinne.\r\nOm en höna blir riktigt rädd lägger den sig ned och låtsas vara död.', 'Höna', 'En del höns får bara sitta inne i små burar och värpa ägg som människor äter. Men höns mår bra av sol och frisk luft. Därför är det bäst om de själva får välja om de vill vara ute eller inne.\r\nHöns trivs bäst i stora grupper med flera hönor, kycklingar och tuppar tillsammans. 25 fåglar är en normal flock. De älskar att gå och sprätta på marken. Men när det blir mörkt vill de vara inne där de är trygga.\r\nTupparna tävlar om vem som är populärast bland hönorna. Det gör de genom att visa hur snygga och starka de är eller genom att ge hönorna mask och annat gott. Vilda höns sover i träd för att slippa rovdjur. Tamhöns sover också högt. Fast de sover på en pinne.'),
('guinea-pig', 'Marsvin är pratglada djur som tycker om sällskap. Det finns många olika sorters marsvin. De kan ha lång päls, kort päls, krullig päls – eller ingen päls alls! Ett marsvin kan bli 8 år.\r\nMarsvin kan ha många olika färger också: från helvita till bruna, gråa, fläckiga och svarta. Marsvin har många ljud för sig. De kan kurra, knorra och vissla. De pratar gärna med varandra och med sin husse eller matte. Ett vuxet marsvin väger cirka 1 kg, ungefär som ett mjölkpaket.\r\nMarsvin är små gnagare och kommer från början från Sydamerika. Där lever de fritt ute i naturen. Om man tar bra hand om sitt marsvin kan det leva upp till 8 år. De får 2-4 ungar per kull.', 'guinea-pig', 'Marsvin tycker bäst om hö, gräs, blad och grönsaker. De tycker också om att gnaga på grenar. Marsvin får lätt ont i magen så det är viktigt att de äter rätt mat. Annars kan de bli sjuka.\r\nMarsvin ska alltid ha tillgång till hö och rent vatten. Ibland kan de också få lite marsvinspellets. Marsvin behöver få extra C-vitamin varje dag. Det går att köpa i djuraffären och hos veterinären.', 'Marsvin har fyra tår på framtassarna, men på baktassarna har de bara tre tår.\r\nEn gång fick ett marsvin 10 ungar! Det är den största kullen man vet om i Sverige.\r\nEn marsvinsunge föds med öppna ögon och öron och kan till och med springa!', 'Marsvin', 'Marsvin är flockdjur och vill leva tillsammans med andra marsvin. De är ganska lugna men vill ändå ha gott om utrymme att röra sig på. På sommaren tycker de om att vara ute och äta gräs.\r\nI naturen lever marsvin i små flockar, alltså flera stycken tillsammans. Ett marsvin som bor själv kan få tråkigt och känna sig ensam. Därför ska man alltid ha minst två marsvin hemma. För att marsvinen ska trivas behöver de ha en stor bur. De tycker också om att få komma ut och springa fritt på golvet. På sommaren kan de vara ute i en bur på gräset. Men om det regnar eller är dåligt väder vill de vara inne. Marsvin får inte bo tillsammans med kaniner, för då kan de bli sjuka.'),
('mini-pig', 'Minigrisar är både keliga och kloka djur. Vissa har dem som husdjur. Minigrisen är släkt med vår vanliga gris som vi får kött och bacon av. Men som man hör på namnet är den mindre.', 'mini-pig', 'Grisens näsa kallas tryne. Trynet använder den för att leta efter rötter, maskar, frön, sniglar och annat gott som finns att äta i marken. Grisar tycker mycket om mat och blir därför lätt tjocka.', 'Grisens päls kallas borst.\r\nI Sverige finns det också vilda grisar. De kallas vildsvin och bor i skogen.\r\nGrisar badar i gyttja och lera för att skydda sig mot solen och mot insekter.\r\nEgentligen är grisar ganska renliga djur. Ändå brukar man säga att man ”grisar ned sig” eller är ”lortig som en gris”.', 'Minigris', 'För att minigrisen ska trivas behöver den få vara ute och böka i marken. Den vill också ha sällskap av andra grisar. Så om man vill ha en minigris måste man bo på landet eller ha en trädgård.'),
('pygmy-goat', 'Dvärggetter är smarta och nyfikna djur. De är också väldigt duktiga på att klättra. Därför kan det vara lite svårt att hålla dem instängda.\r\nDvärggetter är små och kraftiga. Hanarna kallas bockar och ungarna kallas killingar. Både bockar och honor har horn och skägg, men bockarnas är oftast större och längre. Med hornen stångas de ibland. Till exempel när de får mat – då vill alla vara först! Killingarna tycker också om att stångas när de leker för att testa vem som är starkast.\r\nGetmamman föder sina killingar på våren. Oftast får hon två stycken men ibland kan det bli tre.', 'pygmy-goat', 'Dvärggetter tycker mycket om mat och därför blir de lätt tjocka. De tycker om hö, grönsaker och grenar. De vill gärna äta andra saker också, men då kan de få ont i magen.\r\nGetter är kända för att kunna äta nästan vad som helst. Om de får chansen smakar de gärna på nya saker – som kläder, knappar eller kameralock!', 'Både killgetter och tjejgetter har horn och skägg!\r\nMänniskor har haft getter väldigt länge! Redan för 10 000 år sedan hade vi dem som husdjur.\r\nAv getter får vi mjölk som går att dricka eller göra ost av.\r\nGetter har fyra magar – precis som korna!', 'Dvärgget', 'Getter är flockdjur. Det betyder att de inte tycker om att vara ensamma utan vill ha sällskap av andra getter.\r\nGetterna tycker mycket om att vara ute i sin hage. Men när det regnar och är dåligt väder vill de kunna gå in. På vintern behöver de också vara inne ibland och värma sig.'),
('rabbit', 'Kaniner har mjuk päls och starka tänder. De är ganska tysta och pratarhellre med kroppen. Kaniner har starka bakben som de älskar att skutta runt med. De kan också hoppa jättelångt och jättehögt!\r\nDet finns många olika sorters kaniner i många olika färger. Den minsta kaninen är hermelinkaninen som väger mindre än ett mjölkpaket. Den största kaninen – den belgiska jättekaninen – kan väga tio gånger så mycket! Det finns långhåriga och korthåriga kaniner, de kan ha öron som står rakt upp eller som hänger ned. Kaniner kan bli 10 år gamla.\r\nKaniner tycker om när man kelar med dem och kan bli väldigt tama.', 'rabbit', 'Kaniner tycker bäst om hö, som är torkat gräs. De tycker också om färskt gräs, blad, grönsaker och att gnaga på grenar. Kaniner har känsliga magar, så det är viktigt att de äter rätt mat.\r\nDe flesta tror att kaniner äter mycket morötter. Men bäst tycker de faktiskt om bladen på morötterna. De tycker också om maskrosor och knoppar från träd.', 'En kanin äter sin mat två gånger. Först som vanlig mat – och sen som bajs!\r\nOm en kanin blir rädd varnar den andra kaniner genom att stampa hårt med foten i marken. Då springer alla och gömmer sig.\r\nEn kanin kan få många ungar. Om en hona och en hane bor tillsammans kan det bli 800 kaniner på ett år! Då räknar man alla barn, barnbarn och barnbarnsbarn.', 'Kanin', 'I naturen lever kaniner ofta flera hundra tillsammans. Då bor de i gångar och hålor som de gräver under marken. Kaniner tycker om sällskap. Därför ska man gärna ha två om man har dem hemma.\r\nKaniner är trevliga husdjur.De blir ganska lätt rumsrena och kan lära sig att gå på låda. Man kan också lära dem att gå i koppel. Kaniner tycker mycket om att röra på sig. Helst vill de vara utomhus där de kan skutta runt eller beta gräs och gräva gångar i marken.');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
